map/urls.py
from django.urls import path, include
from . import views

app_name = "map.py"

urlpatterns = [
	path('', views.index, name="index"),

]

newsfeed/urls.py
from django.urls import path, re_path
from . import views

app_name = "newsfeed.py"

urlpatterns = [
	# path('', views.post_list, name='post_list'),
	path('', views.PostListView.as_view(), name='post_list'),
	re_path(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
	views.post_detail,
	name='post_detail'),
	re_path(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),

]

sudansite/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('history/', views.history, name="history"),
    path('politics/', views.politics, name="politics"),
    path('culture/', views.culture, name="culture"),
    path('newsfeed/', include("newsfeed.urls", namespace="newsfeed")),
    path('questions/', include("questions.urls", namespace="questions")),
    path('map/', include("map.urls", namespace="map")),
]

templates/base.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head lang="en">
    <meta charset="utf-8">
    <title>The Sudan | {% block title %}{% endblock %}</title>
    <script src="https://use.fontawesome.com/05aaebb2a4.js"></script>
    {% block scripts %}{% endblock %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Lateef" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amiri|Katibeh" rel="stylesheet">
</head>
<body>

<!--Navigation-->
<nav>
    <a href="{% url 'newsfeed:post_list' %}">Newsfeed</a>
    <a href="{% url 'history' %}">History</a>
    <a href="{% url 'politics' %}">Politics</a>
    <h1><a href="{% url 'index' %}">The Sudan السودان</a></h1>
    <a href="{% url 'map:index' %}">Map</a>
    <a href="{% url 'culture' %}">Culture</a>
    <a href="{% url 'questions:index' %}">Contact Us</a>
</nav>

<!--Header-->
<header>
    {% block banner %}
    {% endblock %}
</header>

<!--Primary Page Content-->
<main role="main">
    {% block main_content %}
    {% endblock %}
</main>

<!--Footer & Contact Information-->
<footer>
    <hr />
    <div>
        <a href="#" target="">
            <i class="fa fa-twitter" aria-hidden="true"></i>
            <span class="sr-only">Twitter</span>
        </a>
        <a href="#" target="">
            <i class="fa fa-instagram" aria-hidden="true"></i>
            <span class="sr-only">Instagram</span>
        </a>
        <a href="#" target="">
            <i class="fa fa-facebook" aria-hidden="true"></i>
            <span class="sr-only">Facebook</span>
        </a>
        <a href="#" target="">
            <i class="fa fa-linkedin" aria-hidden="true"></i>
            <span class="sr-only">LinkedIn</span>
        </a>
    </div>
    <p>Copyright 2018 by Ameen Ahmed</p>
</footer>

</body>
</html>